### ISSUE TITLE
Example environment variables are incorrect

### ISSUE THREAD

**Issue by samwmarsh** [SpecterOps/BloodHound#182]
**Description:**

We are attempting to deploy bloodhound-ce using environment variables, to ensure the config isn't stored on disk and increase security. As such, we've been relying on https://github.com/SpecterOps/BloodHound/blob/d9e56dfaf41f35ef399e007a91396ca10e323a98/examples/docker-compose/.env.example to describe the environment variable examples. When attempting to use docker compose, we're seeing issues with these environment variables. An example is the neo4j env vars. No matter how we format these, it returns "invalid neo4j configuration supplied; returning default values". I don't believe anyone has tested these, and therefore they should not be in the main branch of the repository as they cause confusion for no benefit. Examples on formatting would also be helpful in this file so that a user knows what is expected to be within this parameter as it differs from the config.json spec.

**Component(s) Affected:**

- [ ] UI
- [ ] API
- [ ] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [x] Other (tooling, documentation, etc.)

**Steps to Reproduce:**

1. cd to examples/docker-compose
2. update the docker-compose.yml file to attempt to use environment variables as described above in the bloodhound environment block
3. See errors

**Expected Behavior:**

I'd expect the example environment variables to work as described.

**Actual Behavior:**

They don't work as described, and the application defaults back to default credentials, or ends up in a broken state completely.

**Environment Information:**

Latest main branch of this repo.

**Additional Information:**

N/A

**Potential Solution (Optional):**

Have someone review the example environment files, ensure they're all being dealt with correctly and document accordingly. It looks like https://github.com/SpecterOps/BloodHound/pull/99/files attempted to do that but incorrectly. FYI @superlinkx 

**Related Issues:**

https://github.com/SpecterOps/BloodHound/pull/141 was raised to fix some which were overlooked 

**Contributor Checklist:**

- [x] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [x] I have provided clear steps to reproduce the issue.
- [x] I have included relevant environment information details.
- [x] I have attached necessary supporting documents.
- [x] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by superlinkx** [comment]
Ok, after checking a few things, here's what you'll need to know (I'm also preparing some ideas for improving our documentation around this, as well as writing some tickets to improve some rough edges):

- "invalid neo4j configuration supplied; returning default values" is an unfortunately worded error message which should also be a warning (we are working on addressing our log level hygiene, sorry for the mess). The message is only for additional neo4j parameters that we parse from the database as parameters, which are used to control query batch sizing and write flush sizing. I'll flag that these types of errors need to be reworked to be less confusing (in addition to changing to warnings at most, since in most cases they are just expected to use defaults). This is not an error related to any neo4j credentials or other connection based configuration.
- The pieces you need to change the included neo4j container password are as follows (similar for other parameters as well):
    - Copy `.env.example` to `.env`
    - Change the password on the database in `.env` by editing `NEO4J_AUTH`
    - Change the password that BloodHound will use in `.env` by editing `bhe_neo4j_connection`
        - You can use addr/username/secret/database individually, but make sure that there is no `neo4j_connection` being set in both your env vars and the build config. I don't remember which parameters take precedence but I want to say it's `connection`
    - Make sure you clear databases before running, as neo4j will not change its password from an env var if it has already been initialized before (`docker compose down -v`)
    - `docker compose up` and ignore the previously mentioned error
    - If the server starts, then it accepted the connection just fine
- If you'd like to validate that the correct password is in use, you can uncomment the ports section in `docker-compose.yml` for the `graph-db` service and try to use the correct password at `localhost:7474`

The env vars are confirmed working (though `disable_cypher_qc` is now complaining in v5.1.0, so I'm looking into that), there's just some misleading logs and our documentation could use further refinement.

I'll bring up the found issues with the team and we'll triage further.

**Comment by StephenHinck** [comment]
Sounds like this particular issue is solved, and the other things mentioned have other open issues. I'll close this one for now, but please feel free to re-open if that's inaccurate.
