### ISSUE TITLE
Not an issue: Typo

### ISSUE THREAD

**Issue by aleemladha** [SpecterOps/BloodHound#38]
Hi,

kindly replace from "docker compose" command  to "docker-compose"

**Comment by codydbentley** [comment]
The decision to use `docker compose` (v2) instead of `docker-compose` (v1) was intentional. Compose v1 stopped receiving support and has been removed from Docker releases starting after June 2023.

For more information, check out this blog post from Docker:
https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/
