### ISSUE TITLE
ADCS/PKI support

### ISSUE THREAD

**Issue by D00Movenok** [SpecterOps/BloodHound#45]
Hi there! Thank you for awesome work!
Some of the old BloodHound forks supports ADCS/PKI analysis (https://github.com/ly4k/BloodHound). This feature helps to find more lateral movement/privesc paths in the AD and analyze the domain in one place (without jumping between lots of tools).
Do you plan to add this functionality to the community version of BloodHound and/or SharpHound (or integration with [Certipy](https://github.com/ly4k/Certipy))?

**Comment by StephenHinck** [comment]
We are working on a built-in ADCS collection and Attack Path processing capability for BloodHound that will not rely on external tooling. Stay tuned!

**Comment by AkechiShiro** [comment]
Thanks @StephenHinck is there any roadmap or status, such as a project status roadmap showing us the progress or will there be one in the future perhaps ?
So we can see how feature complete is the support ?

**Comment by StephenHinck** [comment]
We are not publishing a full roadmap for BloodHound CE at this time, but are considering that for the future.

**Comment by lawndoc** [comment]
@StephenHinck is there any way for us to contribute to the development of this? Or is this a closed-source component in BHE?

**Comment by lawndoc** [comment]
Looks like this is potentially the work being done on it? https://github.com/BloodHoundAD/SharpHoundCommon/pull/76

**Comment by StephenHinck** [comment]
@lawndoc Feel free to follow along on the currently active branches here:

https://github.com/SpecterOps/BloodHound/tree/adcs-poc
https://github.com/BloodHoundAD/SharpHoundCommon/tree/adcs
https://github.com/BloodHoundAD/SharpHound/tree/adcs

This work is actively ongoing by the BloodHound Engineering team. Unfortunately, at this point in our effort, we won't likely have time to review external contributions to these efforts due to the complexity of the work in progress. We'll be happy to review submissions once the functionality is delivered!

**Comment by StephenHinck** [comment]
This is in Early Access and will be Generally Available with next week's release!

**Comment by lawndoc** [comment]
Great work, BH team! Looking forward to trying it out!
